name: Playwright and K6 Tests by RK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test
        env:
          CI: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Ortoni report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ortoni-report
          path: ortoni-report/
          retention-days: 30

  k6-performance-tests:
    name: K6 Performance Tests
    runs-on: ubuntu-latest
    needs: playwright-tests
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.46.0/k6-v0.46.0-linux-amd64.tar.gz -o k6.tar.gz
          tar -xzf k6.tar.gz
          sudo cp k6-v0.46.0-linux-amd64/k6 /usr/local/bin

      - name: Run K6 performance tests
        run: k6 run tests/perfromance/auth.k6.js

      - name: Copy K6 results to Ortoni report directory
        if: always()
        run: |
          mkdir -p ortoni-report/k6-results
          cp -r k6-results/* ortoni-report/k6-results/ || true
          echo '<iframe src="./k6-results/summary.html" width="100%" height="800px"></iframe>' > ortoni-report/k6-report.html

      - name: Upload K6 results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: k6-results/
          retention-days: 7

  publish-reports:
    name: Publish Reports to GitHub Pages
    runs-on: ubuntu-latest
    needs: [playwright-tests, k6-performance-tests]
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Download Playwright report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: reports/playwright-report

      - name: Download Ortoni report
        uses: actions/download-artifact@v3
        with:
          name: ortoni-report
          path: reports/ortoni-report

      - name: Download K6 results
        uses: actions/download-artifact@v3
        with:
          name: k6-results
          path: reports/k6-results

      - name: Create index page and .nojekyll
        run: |
          mkdir -p reports
          touch reports/.nojekyll
          cat > reports/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Test Reports - Playwright with K6</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { color: #333; }
              .report-link { 
                display: block; 
                margin: 10px 0; 
                padding: 10px; 
                background-color: #f0f0f0; 
                border-radius: 5px;
                text-decoration: none;
                color: #0066cc;
              }
              .report-link:hover { background-color: #e0e0e0; }
            </style>
          </head>
          <body>
            <h1>Test Reports - Playwright with K6</h1>
            <a class="report-link" href="./playwright-report/index.html">Playwright Test Report</a>
            <a class="report-link" href="./ortoni-report/ortoni-report.html">Ortoni Test Report</a>
            <a class="report-link" href="./ortoni-report/k6-report.html">K6 Performance Test Report</a>
            <a class="report-link" href="./k6-results/summary.html">K6 Detailed Results</a>
          </body>
          </html>
          EOL

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
